from .client import (
    EudicError,
    add_note,
    add_word,
    add_words_bulk,
    create_category,
    delete_category,
    delete_note,
    delete_words,
    get_note,
    get_word,
    list_categories,
    list_mastered_words,
    list_notes,
    list_sentences,
    list_words,
    rename_category,
)
from .server import main, server

__all__ = [
    "EudicError",
    "add_note",
    "add_word",
    "add_words_bulk",
    "create_category",
    "delete_category",
    "delete_note",
    "delete_words",
    "get_note",
    "get_word",
    "list_categories",
    "list_mastered_words",
    "list_notes",
    "list_sentences",
    "list_words",
    "rename_category",
    "main",
    "server",
]
